export const BRAND = {
  product: 'SpecSentinel',
  studio: 'SpecSentinel Studio',
  labs: 'SdeAshirvad Labs',
  labsUrl: 'https://labs.sdeashirvad.com/',
  personalUrl: 'https://sdeashirvad.com/',
  personalName: 'Ashirvad Kumar Pandey',
  productUrl: 'https://specsentinel.sdeashirvad.com/',
  githubUrl: 'https://github.com/sdeashirvad/specsentinel',
  docsUrl: 'https://github.com/sdeashirvad/specsentinel/blob/main/README.md',
  npmPackage: 'specsentinel',
  npmUrl: 'https://www.npmjs.com/package/specsentinel',
  npmVersion: '1.0.0',
  npmInstall: 'npm install -g specsentinel',
  socialProof: {
    githubStars: null as number | null,
    npmDownloads: null as string | null,
    latestVersion: '1.0.0',
    latestReleaseDate: null as string | null,
    testsPassing: null as boolean | null,
  },
} as const
