import type { ContractDiffReport } from '../report/ContractDiffReport.js'
import type { DiffChange } from '../models/types.js'

export type PRCommentMode = 'off' | 'summary' | 'full'

const MARKER = '<!-- api-contract-diff-report -->'

const RISK_EMOJI: Record<string, string> = {
  NONE:     '✅',
  LOW:      '🔵',
  MEDIUM:   '🟡',
  HIGH:     '🔴',
  CRITICAL: '🚨',
}

/**
 * Generates a Markdown PR comment body from a ContractDiffReport.
 *
 * mode = 'off'     → returns empty string (caller should not post)
 * mode = 'summary' → compact header + summary table + governance counts
 * mode = 'full'    → (default) full report with collapsible sections + governance detail
 *
 * The comment includes a hidden marker so the GitHub Action can find and
 * update it on subsequent pushes instead of posting duplicate comments.
 */
export function generatePRComment(report: ContractDiffReport, mode: PRCommentMode = 'full'): string {
  if (mode === 'off') return ''
  if (mode === 'summary') return generateSummaryComment(report)
  return generateFullComment(report)
}

// ─── Summary comment ──────────────────────────────────────────────────────────

function generateSummaryComment(report: ContractDiffReport): string {
  const { metadata, summary, riskLevel, riskScore } = report
  const emoji = RISK_EMOJI[riskLevel] ?? '⚠️'
  const g = report.governance

  const lines: string[] = [
    MARKER,
    '',
    `## ${emoji} API Contract Diff — ${riskLevel} Risk`,
    '',
    `**${metadata.oldTitle}** \`v${metadata.oldVersion}\` → \`v${metadata.newVersion}\``,
    '',
    '| Metric | Value |',
    '|--------|-------|',
    `| Total changes | **${summary.total}** |`,
    `| Breaking | **${summary.breaking}** |`,
    `| Non-breaking | **${summary.nonBreaking}** |`,
    `| Risk score | **${riskScore}** (${riskLevel}) |`,
    `| HIGH / MEDIUM / LOW | ${summary.bySeverity.HIGH} / ${summary.bySeverity.MEDIUM} / ${summary.bySeverity.LOW} |`,
  ]

  if (g) {
    lines.push(`| ✅ Approved | **${g.approved}** |`)
    lines.push(`| ⚠️ Expired | **${g.expired}** |`)
    lines.push(`| 🔇 Suppressed | **${g.suppressed}** |`)
    lines.push(`| 🚨 Unapproved Breaking | **${g.unapprovedBreaking}** |`)
  }

  lines.push('')

  if (summary.total === 0) {
    lines.push('> ✅ **No changes detected** — the contracts are identical.')
    lines.push('')
  }

  lines.push('---')
  lines.push(`*Generated by [api-contract-diff](https://github.com/your-org/api-contract-diff) v${report.toolVersion} · ${report.generatedAt.slice(0, 19).replace('T', ' ')} UTC · [Full report mode available]*`)

  return lines.join('\n')
}

// ─── Full comment ─────────────────────────────────────────────────────────────

function generateFullComment(report: ContractDiffReport): string {
  const { metadata, summary, riskLevel, riskScore, changes, impacts } = report
  const emoji = RISK_EMOJI[riskLevel] ?? '⚠️'
  const breaking    = changes.filter(c => c.breaking && c.governanceStatus !== 'SUPPRESSED')
  const nonBreaking = changes.filter(c => !c.breaking && c.governanceStatus !== 'SUPPRESSED')
  const breakingImpacts = impacts.filter(r => r.change.breaking)
  const g = report.governance

  const lines: string[] = [
    MARKER,
    '',
    `## ${emoji} API Contract Diff — ${riskLevel} Risk`,
    '',
    `**${metadata.oldTitle}** \`v${metadata.oldVersion}\` → \`v${metadata.newVersion}\``,
    '',
    '| Metric | Value |',
    '|--------|-------|',
    `| Total changes | **${summary.total}** |`,
    `| Breaking | **${summary.breaking}** |`,
    `| Non-breaking | **${summary.nonBreaking}** |`,
    `| Risk score | **${riskScore}** (${riskLevel}) |`,
    `| HIGH / MEDIUM / LOW | ${summary.bySeverity.HIGH} / ${summary.bySeverity.MEDIUM} / ${summary.bySeverity.LOW} |`,
    '',
  ]

  // ── Governance section ───────────────────────────────────────────────────────
  if (g) {
    const govEmoji = g.unapprovedBreaking > 0 ? '🚨' : g.expired > 0 ? '⚠️' : '🛡️'
    lines.push('<details>')
    lines.push(`<summary>${govEmoji} <strong>Governance Summary</strong> — ${g.approved} approved · ${g.expired} expired · ${g.suppressed} suppressed · ${g.unapprovedBreaking} unapproved</summary>`)
    lines.push('')
    lines.push('| Status | Count |')
    lines.push('|--------|-------|')
    lines.push(`| ✅ Approved | **${g.approved}** |`)
    lines.push(`| ⚠️ Expired approvals | **${g.expired}** |`)
    lines.push(`| 🔇 Suppressed | **${g.suppressed}** |`)
    lines.push(`| 🚨 Unapproved Breaking | **${g.unapprovedBreaking}** |`)
    lines.push('')

    // Approved changes with ownership metadata
    const approvedChanges = changes.filter(c => c.governanceStatus === 'APPROVED')
    if (approvedChanges.length > 0) {
      lines.push('**✅ Approved changes:**')
      lines.push('')
      for (const c of approvedChanges) {
        const m    = c.method ? `\`${c.method.toUpperCase()}\` ` : ''
        const meta = c.governanceMetadata
        lines.push(`- \`[${c.severity}]\` ${m}\`${c.path}\` — ${c.description}`)
        if (meta) {
          lines.push(`  - **Owner:** ${meta.owner}  **Approved by:** ${meta.approvedBy}`)
          lines.push(`  - **Reason:** ${meta.reason}`)
          if (meta.expires) lines.push(`  - **Expires:** ${meta.expires}`)
        }
      }
      lines.push('')
    }

    // Expired approvals
    const expiredChanges = changes.filter(c => c.governanceStatus === 'EXPIRED')
    if (expiredChanges.length > 0) {
      lines.push('**⚠️ Expired approvals — renew in specguard.yml:**')
      lines.push('')
      for (const c of expiredChanges) {
        const m = c.method ? `\`${c.method.toUpperCase()}\` ` : ''
        lines.push(`- \`[${c.severity}]\` ${m}\`${c.path}\` — ${c.description}`)
        if (c.governanceMetadata?.expires) {
          lines.push(`  - **Approval expired:** ${c.governanceMetadata.expires}`)
        }
      }
      lines.push('')
    }

    // Unapproved breaking changes
    const unapprovedChanges = changes.filter(c => c.governanceStatus === 'UNAPPROVED')
    if (unapprovedChanges.length > 0) {
      lines.push('**🚨 Unapproved breaking changes — add entries to specguard.yml:**')
      lines.push('')
      for (const c of unapprovedChanges) {
        const m = c.method ? `\`${c.method.toUpperCase()}\` ` : ''
        lines.push(`- \`[${c.severity}]\` ${m}\`${c.path}\` — ${c.description}`)
      }
      lines.push('')
      lines.push('<details>')
      lines.push('<summary>📋 specguard.yml template for unapproved changes</summary>')
      lines.push('')
      lines.push('```yaml')
      lines.push('approvedChanges:')
      for (const c of unapprovedChanges) {
        const approvalType = changeTypeToApprovalType(c.type)
        lines.push(`  - type: ${approvalType}`)
        lines.push(`    path: "${c.path}"`)
        if (c.method) lines.push(`    method: "${c.method}"`)
        lines.push(`    owner: "your-team"`)
        lines.push(`    approvedBy: "your-lead"`)
        lines.push(`    reason: "TODO: document the reason for this change"`)
        lines.push(`    expires: "2027-01-01"`)
      }
      lines.push('```')
      lines.push('')
      lines.push('</details>')
    }

    if (g.configPath) {
      lines.push(`*Config: \`${g.configPath}\`*`)
      lines.push('')
    }

    lines.push('</details>')
    lines.push('')
  }

  // ── Breaking changes ─────────────────────────────────────────────────────────
  if (breaking.length > 0) {
    lines.push('<details>')
    lines.push(`<summary>🔴 <strong>Breaking Changes (${breaking.length})</strong></summary>`)
    lines.push('')
    lines.push('| Severity | Governance | Method | Path | Description |')
    lines.push('|----------|-----------|--------|------|-------------|')
    for (const c of breaking) {
      lines.push(changeRow(c, true))
    }
    lines.push('')
    lines.push('</details>')
    lines.push('')
  }

  // ── Non-breaking changes ─────────────────────────────────────────────────────
  if (nonBreaking.length > 0) {
    lines.push('<details>')
    lines.push(`<summary>✅ <strong>Non-Breaking Changes (${nonBreaking.length})</strong></summary>`)
    lines.push('')
    lines.push('| Severity | Method | Path | Description |')
    lines.push('|----------|--------|------|-------------|')
    for (const c of nonBreaking) {
      lines.push(changeRow(c, false))
    }
    lines.push('')
    lines.push('</details>')
    lines.push('')
  }

  // ── Consumer impact ──────────────────────────────────────────────────────────
  if (breakingImpacts.length > 0) {
    lines.push('<details>')
    lines.push(`<summary>⚠️ <strong>Consumer Impact Analysis (${breakingImpacts.length} affected)</strong></summary>`)
    lines.push('')
    for (const r of breakingImpacts) {
      const { change, impacts: impactLines } = r
      const method = change.method ? `\`${change.method.toUpperCase()}\` ` : ''
      lines.push(`**${change.severity}** ${method}\`${change.path}\` — ${change.description}`)
      for (const impact of impactLines) {
        lines.push(`- ${impact}`)
      }
      lines.push('')
    }
    lines.push('</details>')
    lines.push('')
  }

  if (summary.total === 0) {
    lines.push('> ✅ **No changes detected** — the contracts are identical.')
    lines.push('')
  }

  lines.push('---')
  lines.push(`*Generated by [api-contract-diff](https://github.com/your-org/api-contract-diff) v${report.toolVersion} at ${report.generatedAt.slice(0, 19).replace('T', ' ')} UTC*`)

  return lines.join('\n')
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function changeRow(c: DiffChange, includeGovernance: boolean): string {
  const method = c.method ? `\`${c.method.toUpperCase()}\`` : '—'
  const govBadge = includeGovernance
    ? (c.governanceStatus === 'APPROVED'   ? '✅' :
       c.governanceStatus === 'EXPIRED'    ? '⚠️' :
       c.governanceStatus === 'UNAPPROVED' ? '🚨' : '—')
    : null
  if (govBadge !== null) {
    return `| ${c.severity} | ${govBadge} | ${method} | \`${c.path}\` | ${c.description} |`
  }
  return `| ${c.severity} | ${method} | \`${c.path}\` | ${c.description} |`
}

/**
 * Maps engine change types back to specguard.yml approval type names.
 */
function changeTypeToApprovalType(changeType: string): string {
  const map: Record<string, string> = {
    'endpoint-removed':      'endpointRemoved',
    'endpoint-added':        'endpointAdded',
    'method-removed':        'methodRemoved',
    'method-added':          'methodAdded',
    'request-field-removed': 'requestFieldRemoved',
    'response-field-removed':'responseFieldRemoved',
    'request-field-added':   'requestFieldAdded',
    'response-field-added':  'responseFieldAdded',
    'field-type-changed':    'typeChanged',
    'field-required-changed':'requiredChanged',
    'enum-value-removed':    'enumRemoved',
    'enum-value-added':      'enumAdded',
    'status-code-removed':   'statusCodeRemoved',
    'status-code-added':     'statusCodeAdded',
  }
  return map[changeType] ?? changeType
}

/**
 * Returns the hidden marker string used to identify existing bot comments.
 * GitHub Action uses this to find and update the comment in place.
 */
export function getPRCommentMarker(): string {
  return MARKER
}
